// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: kk_scheduler/extend_field.proto

package kk_scheduler

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FieldBehavior int32

const (
	FieldBehavior_FIELD_BEHAVIOR_UNSPECIFIED FieldBehavior = 0
	FieldBehavior_REQUIRED                   FieldBehavior = 1
	// https://github.com/googleapis/googleapis/blob/master/google/api/field_info.proto
	FieldBehavior_UUID7 FieldBehavior = 2
	// https://github.com/googleapis/googleapis/blob/master/google/api/field_info.proto
	FieldBehavior_IPV4_OR_IPV6 FieldBehavior = 3
)

// Enum value maps for FieldBehavior.
var (
	FieldBehavior_name = map[int32]string{
		0: "FIELD_BEHAVIOR_UNSPECIFIED",
		1: "REQUIRED",
		2: "UUID7",
		3: "IPV4_OR_IPV6",
	}
	FieldBehavior_value = map[string]int32{
		"FIELD_BEHAVIOR_UNSPECIFIED": 0,
		"REQUIRED":                   1,
		"UUID7":                      2,
		"IPV4_OR_IPV6":               3,
	}
)

func (x FieldBehavior) Enum() *FieldBehavior {
	p := new(FieldBehavior)
	*p = x
	return p
}

func (x FieldBehavior) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FieldBehavior) Descriptor() protoreflect.EnumDescriptor {
	return file_kk_scheduler_extend_field_proto_enumTypes[0].Descriptor()
}

func (FieldBehavior) Type() protoreflect.EnumType {
	return &file_kk_scheduler_extend_field_proto_enumTypes[0]
}

func (x FieldBehavior) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

var file_kk_scheduler_extend_field_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: ([]FieldBehavior)(nil),
		Field:         1001,
		Name:          "kk_scheduler.field_behavior",
		Tag:           "varint,1001,rep,packed,name=field_behavior,enum=kk_scheduler.FieldBehavior",
		Filename:      "kk_scheduler/extend_field.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// repeated kk_scheduler.FieldBehavior field_behavior = 1001;
	E_FieldBehavior = &file_kk_scheduler_extend_field_proto_extTypes[0]
)

var File_kk_scheduler_extend_field_proto protoreflect.FileDescriptor

const file_kk_scheduler_extend_field_proto_rawDesc = "" +
	"\n" +
	"\x1fkk_scheduler/extend_field.proto\x12\fkk_scheduler\x1a google/protobuf/descriptor.proto*Z\n" +
	"\rFieldBehavior\x12\x1e\n" +
	"\x1aFIELD_BEHAVIOR_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bREQUIRED\x10\x01\x12\t\n" +
	"\x05UUID7\x10\x02\x12\x10\n" +
	"\fIPV4_OR_IPV6\x10\x03:b\n" +
	"\x0efield_behavior\x12\x1d.google.protobuf.FieldOptions\x18\xe9\a \x03(\x0e2\x1b.kk_scheduler.FieldBehaviorR\rfieldBehaviorB\x0fZ\r/kk_schedulerb\beditionsp\xe8\a"

var file_kk_scheduler_extend_field_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_kk_scheduler_extend_field_proto_goTypes = []any{
	(FieldBehavior)(0),                // 0: kk_scheduler.FieldBehavior
	(*descriptorpb.FieldOptions)(nil), // 1: google.protobuf.FieldOptions
}
var file_kk_scheduler_extend_field_proto_depIdxs = []int32{
	1, // 0: kk_scheduler.field_behavior:extendee -> google.protobuf.FieldOptions
	0, // 1: kk_scheduler.field_behavior:type_name -> kk_scheduler.FieldBehavior
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kk_scheduler_extend_field_proto_init() }
func file_kk_scheduler_extend_field_proto_init() {
	if File_kk_scheduler_extend_field_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kk_scheduler_extend_field_proto_rawDesc), len(file_kk_scheduler_extend_field_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_kk_scheduler_extend_field_proto_goTypes,
		DependencyIndexes: file_kk_scheduler_extend_field_proto_depIdxs,
		EnumInfos:         file_kk_scheduler_extend_field_proto_enumTypes,
		ExtensionInfos:    file_kk_scheduler_extend_field_proto_extTypes,
	}.Build()
	File_kk_scheduler_extend_field_proto = out.File
	file_kk_scheduler_extend_field_proto_goTypes = nil
	file_kk_scheduler_extend_field_proto_depIdxs = nil
}
