// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: kk_scheduler/rpc_service.proto

package kk_scheduler

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Trigger struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trigger) Reset() {
	*x = Trigger{}
	mi := &file_kk_scheduler_rpc_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trigger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trigger) ProtoMessage() {}

func (x *Trigger) ProtoReflect() protoreflect.Message {
	mi := &file_kk_scheduler_rpc_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type Trigger_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 Trigger_builder) Build() *Trigger {
	m0 := &Trigger{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type Trigger_Input struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_FuncName    *string                `protobuf:"bytes,1,opt,name=funcName"`
	xxx_hidden_JobId       *string                `protobuf:"bytes,2,opt,name=jobId"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Trigger_Input) Reset() {
	*x = Trigger_Input{}
	mi := &file_kk_scheduler_rpc_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trigger_Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trigger_Input) ProtoMessage() {}

func (x *Trigger_Input) ProtoReflect() protoreflect.Message {
	mi := &file_kk_scheduler_rpc_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Trigger_Input) GetFuncName() string {
	if x != nil {
		if x.xxx_hidden_FuncName != nil {
			return *x.xxx_hidden_FuncName
		}
		return ""
	}
	return ""
}

func (x *Trigger_Input) GetJobId() string {
	if x != nil {
		if x.xxx_hidden_JobId != nil {
			return *x.xxx_hidden_JobId
		}
		return ""
	}
	return ""
}

func (x *Trigger_Input) SetFuncName(v string) {
	x.xxx_hidden_FuncName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *Trigger_Input) SetJobId(v string) {
	x.xxx_hidden_JobId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *Trigger_Input) HasFuncName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Trigger_Input) HasJobId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Trigger_Input) ClearFuncName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_FuncName = nil
}

func (x *Trigger_Input) ClearJobId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_JobId = nil
}

type Trigger_Input_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	FuncName *string
	JobId    *string
}

func (b0 Trigger_Input_builder) Build() *Trigger_Input {
	m0 := &Trigger_Input{}
	b, x := &b0, m0
	_, _ = b, x
	if b.FuncName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_FuncName = b.FuncName
	}
	if b.JobId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_JobId = b.JobId
	}
	return m0
}

type Trigger_Output struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trigger_Output) Reset() {
	*x = Trigger_Output{}
	mi := &file_kk_scheduler_rpc_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trigger_Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trigger_Output) ProtoMessage() {}

func (x *Trigger_Output) ProtoReflect() protoreflect.Message {
	mi := &file_kk_scheduler_rpc_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type Trigger_Output_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 Trigger_Output_builder) Build() *Trigger_Output {
	m0 := &Trigger_Output{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_kk_scheduler_rpc_service_proto protoreflect.FileDescriptor

const file_kk_scheduler_rpc_service_proto_rawDesc = "" +
	"\n" +
	"\x1ekk_scheduler/rpc_service.proto\x12\fkk_scheduler\x1a\x16kk_scheduler/Job.proto\x1a\x1akk_scheduler/Service.proto\x1a kk_scheduler/TaskExecution.proto\x1a\x1fkk_scheduler/extend_field.proto\"U\n" +
	"\aTrigger\x1a@\n" +
	"\x05Input\x12\x1a\n" +
	"\bfuncName\x18\x01 \x01(\tR\bfuncName\x12\x1b\n" +
	"\x05jobId\x18\x02 \x01(\tB\x05\xca>\x02\x01\x02R\x05jobId\x1a\b\n" +
	"\x06Output2\xdc\v\n" +
	"\n" +
	"KKSchedule\x12D\n" +
	"\aJobList\x12\x1b.kk_scheduler.JobList.Input\x1a\x1c.kk_scheduler.JobList.Output\x12A\n" +
	"\x06JobGet\x12\x1a.kk_scheduler.JobGet.Input\x1a\x1b.kk_scheduler.JobGet.Output\x12M\n" +
	"\n" +
	"JobSetSpec\x12\x1e.kk_scheduler.JobSetSpec.Input\x1a\x1f.kk_scheduler.JobSetSpec.Output\x12J\n" +
	"\tJobEnable\x12\x1d.kk_scheduler.JobEnable.Input\x1a\x1e.kk_scheduler.JobEnable.Output\x12M\n" +
	"\n" +
	"JobDisable\x12\x1e.kk_scheduler.JobDisable.Input\x1a\x1f.kk_scheduler.JobDisable.Output\x12A\n" +
	"\x06JobPut\x12\x1a.kk_scheduler.JobPut.Input\x1a\x1b.kk_scheduler.JobPut.Output\x12J\n" +
	"\tJobDelete\x12\x1d.kk_scheduler.JobDelete.Input\x1a\x1e.kk_scheduler.JobDelete.Output\x12M\n" +
	"\n" +
	"JobTrigger\x12\x1e.kk_scheduler.JobTrigger.Input\x1a\x1f.kk_scheduler.JobTrigger.Output\x12P\n" +
	"\vServiceList\x12\x1f.kk_scheduler.ServiceList.Input\x1a .kk_scheduler.ServiceList.Output\x12M\n" +
	"\n" +
	"ServicePut\x12\x1e.kk_scheduler.ServicePut.Input\x1a\x1f.kk_scheduler.ServicePut.Output\x12M\n" +
	"\n" +
	"ServiceGet\x12\x1e.kk_scheduler.ServiceGet.Input\x1a\x1f.kk_scheduler.ServiceGet.Output\x12V\n" +
	"\rServiceDelete\x12!.kk_scheduler.ServiceDelete.Input\x1a\".kk_scheduler.ServiceDelete.Output\x12M\n" +
	"\n" +
	"TaskCreate\x12\x1e.kk_scheduler.TaskCreate.Input\x1a\x1f.kk_scheduler.TaskCreate.Output\x12_\n" +
	"\x10TaskUpdateStatus\x12$.kk_scheduler.TaskUpdateStatus.Input\x1a%.kk_scheduler.TaskUpdateStatus.Output\x12V\n" +
	"\rTaskAppendLog\x12!.kk_scheduler.TaskAppendLog.Input\x1a\".kk_scheduler.TaskAppendLog.Output\x12b\n" +
	"\x11TaskExecutionList\x12%.kk_scheduler.TaskExecutionList.Input\x1a&.kk_scheduler.TaskExecutionList.Output\x12_\n" +
	"\x10TaskExecutionGet\x12$.kk_scheduler.TaskExecutionGet.Input\x1a%.kk_scheduler.TaskExecutionGet.Output\x12h\n" +
	"\x13TaskExecutionDelete\x12'.kk_scheduler.TaskExecutionDelete.Input\x1a(.kk_scheduler.TaskExecutionDelete.Output2Y\n" +
	"\x11KKScheduleTrigger\x12D\n" +
	"\aTrigger\x12\x1b.kk_scheduler.Trigger.Input\x1a\x1c.kk_scheduler.Trigger.OutputB\x0fZ\r/kk_schedulerb\beditionsp\xe8\a"

var file_kk_scheduler_rpc_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_kk_scheduler_rpc_service_proto_goTypes = []any{
	(*Trigger)(nil),                    // 0: kk_scheduler.Trigger
	(*Trigger_Input)(nil),              // 1: kk_scheduler.Trigger.Input
	(*Trigger_Output)(nil),             // 2: kk_scheduler.Trigger.Output
	(*JobList_Input)(nil),              // 3: kk_scheduler.JobList.Input
	(*JobGet_Input)(nil),               // 4: kk_scheduler.JobGet.Input
	(*JobSetSpec_Input)(nil),           // 5: kk_scheduler.JobSetSpec.Input
	(*JobEnable_Input)(nil),            // 6: kk_scheduler.JobEnable.Input
	(*JobDisable_Input)(nil),           // 7: kk_scheduler.JobDisable.Input
	(*JobPut_Input)(nil),               // 8: kk_scheduler.JobPut.Input
	(*JobDelete_Input)(nil),            // 9: kk_scheduler.JobDelete.Input
	(*JobTrigger_Input)(nil),           // 10: kk_scheduler.JobTrigger.Input
	(*ServiceList_Input)(nil),          // 11: kk_scheduler.ServiceList.Input
	(*ServicePut_Input)(nil),           // 12: kk_scheduler.ServicePut.Input
	(*ServiceGet_Input)(nil),           // 13: kk_scheduler.ServiceGet.Input
	(*ServiceDelete_Input)(nil),        // 14: kk_scheduler.ServiceDelete.Input
	(*TaskCreate_Input)(nil),           // 15: kk_scheduler.TaskCreate.Input
	(*TaskUpdateStatus_Input)(nil),     // 16: kk_scheduler.TaskUpdateStatus.Input
	(*TaskAppendLog_Input)(nil),        // 17: kk_scheduler.TaskAppendLog.Input
	(*TaskExecutionList_Input)(nil),    // 18: kk_scheduler.TaskExecutionList.Input
	(*TaskExecutionGet_Input)(nil),     // 19: kk_scheduler.TaskExecutionGet.Input
	(*TaskExecutionDelete_Input)(nil),  // 20: kk_scheduler.TaskExecutionDelete.Input
	(*JobList_Output)(nil),             // 21: kk_scheduler.JobList.Output
	(*JobGet_Output)(nil),              // 22: kk_scheduler.JobGet.Output
	(*JobSetSpec_Output)(nil),          // 23: kk_scheduler.JobSetSpec.Output
	(*JobEnable_Output)(nil),           // 24: kk_scheduler.JobEnable.Output
	(*JobDisable_Output)(nil),          // 25: kk_scheduler.JobDisable.Output
	(*JobPut_Output)(nil),              // 26: kk_scheduler.JobPut.Output
	(*JobDelete_Output)(nil),           // 27: kk_scheduler.JobDelete.Output
	(*JobTrigger_Output)(nil),          // 28: kk_scheduler.JobTrigger.Output
	(*ServiceList_Output)(nil),         // 29: kk_scheduler.ServiceList.Output
	(*ServicePut_Output)(nil),          // 30: kk_scheduler.ServicePut.Output
	(*ServiceGet_Output)(nil),          // 31: kk_scheduler.ServiceGet.Output
	(*ServiceDelete_Output)(nil),       // 32: kk_scheduler.ServiceDelete.Output
	(*TaskCreate_Output)(nil),          // 33: kk_scheduler.TaskCreate.Output
	(*TaskUpdateStatus_Output)(nil),    // 34: kk_scheduler.TaskUpdateStatus.Output
	(*TaskAppendLog_Output)(nil),       // 35: kk_scheduler.TaskAppendLog.Output
	(*TaskExecutionList_Output)(nil),   // 36: kk_scheduler.TaskExecutionList.Output
	(*TaskExecutionGet_Output)(nil),    // 37: kk_scheduler.TaskExecutionGet.Output
	(*TaskExecutionDelete_Output)(nil), // 38: kk_scheduler.TaskExecutionDelete.Output
}
var file_kk_scheduler_rpc_service_proto_depIdxs = []int32{
	3,  // 0: kk_scheduler.KKSchedule.JobList:input_type -> kk_scheduler.JobList.Input
	4,  // 1: kk_scheduler.KKSchedule.JobGet:input_type -> kk_scheduler.JobGet.Input
	5,  // 2: kk_scheduler.KKSchedule.JobSetSpec:input_type -> kk_scheduler.JobSetSpec.Input
	6,  // 3: kk_scheduler.KKSchedule.JobEnable:input_type -> kk_scheduler.JobEnable.Input
	7,  // 4: kk_scheduler.KKSchedule.JobDisable:input_type -> kk_scheduler.JobDisable.Input
	8,  // 5: kk_scheduler.KKSchedule.JobPut:input_type -> kk_scheduler.JobPut.Input
	9,  // 6: kk_scheduler.KKSchedule.JobDelete:input_type -> kk_scheduler.JobDelete.Input
	10, // 7: kk_scheduler.KKSchedule.JobTrigger:input_type -> kk_scheduler.JobTrigger.Input
	11, // 8: kk_scheduler.KKSchedule.ServiceList:input_type -> kk_scheduler.ServiceList.Input
	12, // 9: kk_scheduler.KKSchedule.ServicePut:input_type -> kk_scheduler.ServicePut.Input
	13, // 10: kk_scheduler.KKSchedule.ServiceGet:input_type -> kk_scheduler.ServiceGet.Input
	14, // 11: kk_scheduler.KKSchedule.ServiceDelete:input_type -> kk_scheduler.ServiceDelete.Input
	15, // 12: kk_scheduler.KKSchedule.TaskCreate:input_type -> kk_scheduler.TaskCreate.Input
	16, // 13: kk_scheduler.KKSchedule.TaskUpdateStatus:input_type -> kk_scheduler.TaskUpdateStatus.Input
	17, // 14: kk_scheduler.KKSchedule.TaskAppendLog:input_type -> kk_scheduler.TaskAppendLog.Input
	18, // 15: kk_scheduler.KKSchedule.TaskExecutionList:input_type -> kk_scheduler.TaskExecutionList.Input
	19, // 16: kk_scheduler.KKSchedule.TaskExecutionGet:input_type -> kk_scheduler.TaskExecutionGet.Input
	20, // 17: kk_scheduler.KKSchedule.TaskExecutionDelete:input_type -> kk_scheduler.TaskExecutionDelete.Input
	1,  // 18: kk_scheduler.KKScheduleTrigger.Trigger:input_type -> kk_scheduler.Trigger.Input
	21, // 19: kk_scheduler.KKSchedule.JobList:output_type -> kk_scheduler.JobList.Output
	22, // 20: kk_scheduler.KKSchedule.JobGet:output_type -> kk_scheduler.JobGet.Output
	23, // 21: kk_scheduler.KKSchedule.JobSetSpec:output_type -> kk_scheduler.JobSetSpec.Output
	24, // 22: kk_scheduler.KKSchedule.JobEnable:output_type -> kk_scheduler.JobEnable.Output
	25, // 23: kk_scheduler.KKSchedule.JobDisable:output_type -> kk_scheduler.JobDisable.Output
	26, // 24: kk_scheduler.KKSchedule.JobPut:output_type -> kk_scheduler.JobPut.Output
	27, // 25: kk_scheduler.KKSchedule.JobDelete:output_type -> kk_scheduler.JobDelete.Output
	28, // 26: kk_scheduler.KKSchedule.JobTrigger:output_type -> kk_scheduler.JobTrigger.Output
	29, // 27: kk_scheduler.KKSchedule.ServiceList:output_type -> kk_scheduler.ServiceList.Output
	30, // 28: kk_scheduler.KKSchedule.ServicePut:output_type -> kk_scheduler.ServicePut.Output
	31, // 29: kk_scheduler.KKSchedule.ServiceGet:output_type -> kk_scheduler.ServiceGet.Output
	32, // 30: kk_scheduler.KKSchedule.ServiceDelete:output_type -> kk_scheduler.ServiceDelete.Output
	33, // 31: kk_scheduler.KKSchedule.TaskCreate:output_type -> kk_scheduler.TaskCreate.Output
	34, // 32: kk_scheduler.KKSchedule.TaskUpdateStatus:output_type -> kk_scheduler.TaskUpdateStatus.Output
	35, // 33: kk_scheduler.KKSchedule.TaskAppendLog:output_type -> kk_scheduler.TaskAppendLog.Output
	36, // 34: kk_scheduler.KKSchedule.TaskExecutionList:output_type -> kk_scheduler.TaskExecutionList.Output
	37, // 35: kk_scheduler.KKSchedule.TaskExecutionGet:output_type -> kk_scheduler.TaskExecutionGet.Output
	38, // 36: kk_scheduler.KKSchedule.TaskExecutionDelete:output_type -> kk_scheduler.TaskExecutionDelete.Output
	2,  // 37: kk_scheduler.KKScheduleTrigger.Trigger:output_type -> kk_scheduler.Trigger.Output
	19, // [19:38] is the sub-list for method output_type
	0,  // [0:19] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_kk_scheduler_rpc_service_proto_init() }
func file_kk_scheduler_rpc_service_proto_init() {
	if File_kk_scheduler_rpc_service_proto != nil {
		return
	}
	file_kk_scheduler_Job_proto_init()
	file_kk_scheduler_Service_proto_init()
	file_kk_scheduler_TaskExecution_proto_init()
	file_kk_scheduler_extend_field_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kk_scheduler_rpc_service_proto_rawDesc), len(file_kk_scheduler_rpc_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_kk_scheduler_rpc_service_proto_goTypes,
		DependencyIndexes: file_kk_scheduler_rpc_service_proto_depIdxs,
		MessageInfos:      file_kk_scheduler_rpc_service_proto_msgTypes,
	}.Build()
	File_kk_scheduler_rpc_service_proto = out.File
	file_kk_scheduler_rpc_service_proto_goTypes = nil
	file_kk_scheduler_rpc_service_proto_depIdxs = nil
}
