// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: kk_scheduler/Service.proto

package kk_scheduler

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServiceList struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceList) Reset() {
	*x = ServiceList{}
	mi := &file_kk_scheduler_Service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceList) ProtoMessage() {}

func (x *ServiceList) ProtoReflect() protoreflect.Message {
	mi := &file_kk_scheduler_Service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ServiceList_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ServiceList_builder) Build() *ServiceList {
	m0 := &ServiceList{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type ServiceDelete struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceDelete) Reset() {
	*x = ServiceDelete{}
	mi := &file_kk_scheduler_Service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceDelete) ProtoMessage() {}

func (x *ServiceDelete) ProtoReflect() protoreflect.Message {
	mi := &file_kk_scheduler_Service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ServiceDelete_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ServiceDelete_builder) Build() *ServiceDelete {
	m0 := &ServiceDelete{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type ServiceGet struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceGet) Reset() {
	*x = ServiceGet{}
	mi := &file_kk_scheduler_Service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceGet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceGet) ProtoMessage() {}

func (x *ServiceGet) ProtoReflect() protoreflect.Message {
	mi := &file_kk_scheduler_Service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ServiceGet_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ServiceGet_builder) Build() *ServiceGet {
	m0 := &ServiceGet{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type ServicePut struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServicePut) Reset() {
	*x = ServicePut{}
	mi := &file_kk_scheduler_Service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServicePut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServicePut) ProtoMessage() {}

func (x *ServicePut) ProtoReflect() protoreflect.Message {
	mi := &file_kk_scheduler_Service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ServicePut_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ServicePut_builder) Build() *ServicePut {
	m0 := &ServicePut{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type ServiceList_Input struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceList_Input) Reset() {
	*x = ServiceList_Input{}
	mi := &file_kk_scheduler_Service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceList_Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceList_Input) ProtoMessage() {}

func (x *ServiceList_Input) ProtoReflect() protoreflect.Message {
	mi := &file_kk_scheduler_Service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ServiceList_Input_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ServiceList_Input_builder) Build() *ServiceList_Input {
	m0 := &ServiceList_Input{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type ServiceList_Output struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ServiceList *[]*PBRegisterService  `protobuf:"bytes,1,rep,name=ServiceList"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ServiceList_Output) Reset() {
	*x = ServiceList_Output{}
	mi := &file_kk_scheduler_Service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceList_Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceList_Output) ProtoMessage() {}

func (x *ServiceList_Output) ProtoReflect() protoreflect.Message {
	mi := &file_kk_scheduler_Service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ServiceList_Output) GetServiceList() []*PBRegisterService {
	if x != nil {
		if x.xxx_hidden_ServiceList != nil {
			return *x.xxx_hidden_ServiceList
		}
	}
	return nil
}

func (x *ServiceList_Output) SetServiceList(v []*PBRegisterService) {
	x.xxx_hidden_ServiceList = &v
}

type ServiceList_Output_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ServiceList []*PBRegisterService
}

func (b0 ServiceList_Output_builder) Build() *ServiceList_Output {
	m0 := &ServiceList_Output{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ServiceList = &b.ServiceList
	return m0
}

type ServiceDelete_Input struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ServiceName *string                `protobuf:"bytes,1,opt,name=ServiceName"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ServiceDelete_Input) Reset() {
	*x = ServiceDelete_Input{}
	mi := &file_kk_scheduler_Service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceDelete_Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceDelete_Input) ProtoMessage() {}

func (x *ServiceDelete_Input) ProtoReflect() protoreflect.Message {
	mi := &file_kk_scheduler_Service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ServiceDelete_Input) GetServiceName() string {
	if x != nil {
		if x.xxx_hidden_ServiceName != nil {
			return *x.xxx_hidden_ServiceName
		}
		return ""
	}
	return ""
}

func (x *ServiceDelete_Input) SetServiceName(v string) {
	x.xxx_hidden_ServiceName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *ServiceDelete_Input) HasServiceName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ServiceDelete_Input) ClearServiceName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_ServiceName = nil
}

type ServiceDelete_Input_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ServiceName *string
}

func (b0 ServiceDelete_Input_builder) Build() *ServiceDelete_Input {
	m0 := &ServiceDelete_Input{}
	b, x := &b0, m0
	_, _ = b, x
	if b.ServiceName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_ServiceName = b.ServiceName
	}
	return m0
}

type ServiceDelete_Output struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceDelete_Output) Reset() {
	*x = ServiceDelete_Output{}
	mi := &file_kk_scheduler_Service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceDelete_Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceDelete_Output) ProtoMessage() {}

func (x *ServiceDelete_Output) ProtoReflect() protoreflect.Message {
	mi := &file_kk_scheduler_Service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ServiceDelete_Output_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ServiceDelete_Output_builder) Build() *ServiceDelete_Output {
	m0 := &ServiceDelete_Output{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type ServiceGet_Input struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ServiceName *string                `protobuf:"bytes,1,opt,name=ServiceName"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ServiceGet_Input) Reset() {
	*x = ServiceGet_Input{}
	mi := &file_kk_scheduler_Service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceGet_Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceGet_Input) ProtoMessage() {}

func (x *ServiceGet_Input) ProtoReflect() protoreflect.Message {
	mi := &file_kk_scheduler_Service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ServiceGet_Input) GetServiceName() string {
	if x != nil {
		if x.xxx_hidden_ServiceName != nil {
			return *x.xxx_hidden_ServiceName
		}
		return ""
	}
	return ""
}

func (x *ServiceGet_Input) SetServiceName(v string) {
	x.xxx_hidden_ServiceName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *ServiceGet_Input) HasServiceName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ServiceGet_Input) ClearServiceName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_ServiceName = nil
}

type ServiceGet_Input_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// ServiceName, leave empty to get all services
	ServiceName *string
}

func (b0 ServiceGet_Input_builder) Build() *ServiceGet_Input {
	m0 := &ServiceGet_Input{}
	b, x := &b0, m0
	_, _ = b, x
	if b.ServiceName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_ServiceName = b.ServiceName
	}
	return m0
}

type ServiceGet_Output struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Service *PBRegisterService     `protobuf:"bytes,1,opt,name=Service"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ServiceGet_Output) Reset() {
	*x = ServiceGet_Output{}
	mi := &file_kk_scheduler_Service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceGet_Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceGet_Output) ProtoMessage() {}

func (x *ServiceGet_Output) ProtoReflect() protoreflect.Message {
	mi := &file_kk_scheduler_Service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ServiceGet_Output) GetService() *PBRegisterService {
	if x != nil {
		return x.xxx_hidden_Service
	}
	return nil
}

func (x *ServiceGet_Output) SetService(v *PBRegisterService) {
	x.xxx_hidden_Service = v
}

func (x *ServiceGet_Output) HasService() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Service != nil
}

func (x *ServiceGet_Output) ClearService() {
	x.xxx_hidden_Service = nil
}

type ServiceGet_Output_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Service *PBRegisterService
}

func (b0 ServiceGet_Output_builder) Build() *ServiceGet_Output {
	m0 := &ServiceGet_Output{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Service = b.Service
	return m0
}

type ServicePut_Input struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Service *PBRegisterService     `protobuf:"bytes,1,opt,name=Service"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ServicePut_Input) Reset() {
	*x = ServicePut_Input{}
	mi := &file_kk_scheduler_Service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServicePut_Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServicePut_Input) ProtoMessage() {}

func (x *ServicePut_Input) ProtoReflect() protoreflect.Message {
	mi := &file_kk_scheduler_Service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ServicePut_Input) GetService() *PBRegisterService {
	if x != nil {
		return x.xxx_hidden_Service
	}
	return nil
}

func (x *ServicePut_Input) SetService(v *PBRegisterService) {
	x.xxx_hidden_Service = v
}

func (x *ServicePut_Input) HasService() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Service != nil
}

func (x *ServicePut_Input) ClearService() {
	x.xxx_hidden_Service = nil
}

type ServicePut_Input_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Service *PBRegisterService
}

func (b0 ServicePut_Input_builder) Build() *ServicePut_Input {
	m0 := &ServicePut_Input{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Service = b.Service
	return m0
}

type ServicePut_Output struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServicePut_Output) Reset() {
	*x = ServicePut_Output{}
	mi := &file_kk_scheduler_Service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServicePut_Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServicePut_Output) ProtoMessage() {}

func (x *ServicePut_Output) ProtoReflect() protoreflect.Message {
	mi := &file_kk_scheduler_Service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ServicePut_Output_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ServicePut_Output_builder) Build() *ServicePut_Output {
	m0 := &ServicePut_Output{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_kk_scheduler_Service_proto protoreflect.FileDescriptor

const file_kk_scheduler_Service_proto_rawDesc = "" +
	"\n" +
	"\x1akk_scheduler/Service.proto\x12\fkk_scheduler\x1a\x17kk_scheduler/Base.proto\"c\n" +
	"\vServiceList\x1a\a\n" +
	"\x05Input\x1aK\n" +
	"\x06Output\x12A\n" +
	"\vServiceList\x18\x01 \x03(\v2\x1f.kk_scheduler.PBRegisterServiceR\vServiceList\"D\n" +
	"\rServiceDelete\x1a)\n" +
	"\x05Input\x12 \n" +
	"\vServiceName\x18\x01 \x01(\tR\vServiceName\x1a\b\n" +
	"\x06Output\"|\n" +
	"\n" +
	"ServiceGet\x1a)\n" +
	"\x05Input\x12 \n" +
	"\vServiceName\x18\x01 \x01(\tR\vServiceName\x1aC\n" +
	"\x06Output\x129\n" +
	"\aService\x18\x01 \x01(\v2\x1f.kk_scheduler.PBRegisterServiceR\aService\"Z\n" +
	"\n" +
	"ServicePut\x1aB\n" +
	"\x05Input\x129\n" +
	"\aService\x18\x01 \x01(\v2\x1f.kk_scheduler.PBRegisterServiceR\aService\x1a\b\n" +
	"\x06OutputB\x0fZ\r/kk_schedulerb\beditionsp\xe8\a"

var file_kk_scheduler_Service_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_kk_scheduler_Service_proto_goTypes = []any{
	(*ServiceList)(nil),          // 0: kk_scheduler.ServiceList
	(*ServiceDelete)(nil),        // 1: kk_scheduler.ServiceDelete
	(*ServiceGet)(nil),           // 2: kk_scheduler.ServiceGet
	(*ServicePut)(nil),           // 3: kk_scheduler.ServicePut
	(*ServiceList_Input)(nil),    // 4: kk_scheduler.ServiceList.Input
	(*ServiceList_Output)(nil),   // 5: kk_scheduler.ServiceList.Output
	(*ServiceDelete_Input)(nil),  // 6: kk_scheduler.ServiceDelete.Input
	(*ServiceDelete_Output)(nil), // 7: kk_scheduler.ServiceDelete.Output
	(*ServiceGet_Input)(nil),     // 8: kk_scheduler.ServiceGet.Input
	(*ServiceGet_Output)(nil),    // 9: kk_scheduler.ServiceGet.Output
	(*ServicePut_Input)(nil),     // 10: kk_scheduler.ServicePut.Input
	(*ServicePut_Output)(nil),    // 11: kk_scheduler.ServicePut.Output
	(*PBRegisterService)(nil),    // 12: kk_scheduler.PBRegisterService
}
var file_kk_scheduler_Service_proto_depIdxs = []int32{
	12, // 0: kk_scheduler.ServiceList.Output.ServiceList:type_name -> kk_scheduler.PBRegisterService
	12, // 1: kk_scheduler.ServiceGet.Output.Service:type_name -> kk_scheduler.PBRegisterService
	12, // 2: kk_scheduler.ServicePut.Input.Service:type_name -> kk_scheduler.PBRegisterService
	3,  // [3:3] is the sub-list for method output_type
	3,  // [3:3] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_kk_scheduler_Service_proto_init() }
func file_kk_scheduler_Service_proto_init() {
	if File_kk_scheduler_Service_proto != nil {
		return
	}
	file_kk_scheduler_Base_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kk_scheduler_Service_proto_rawDesc), len(file_kk_scheduler_Service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kk_scheduler_Service_proto_goTypes,
		DependencyIndexes: file_kk_scheduler_Service_proto_depIdxs,
		MessageInfos:      file_kk_scheduler_Service_proto_msgTypes,
	}.Build()
	File_kk_scheduler_Service_proto = out.File
	file_kk_scheduler_Service_proto_goTypes = nil
	file_kk_scheduler_Service_proto_depIdxs = nil
}
