// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/cruvie/kk-scheduler/go/internal/models"
)

func newTaskExecution(db *gorm.DB, opts ...gen.DOOption) taskExecution {
	_taskExecution := taskExecution{}

	_taskExecution.taskExecutionDo.UseDB(db, opts...)
	_taskExecution.taskExecutionDo.UseModel(&models.TaskExecution{})

	tableName := _taskExecution.taskExecutionDo.TableName()
	_taskExecution.ALL = field.NewAsterisk(tableName)
	_taskExecution.Id = field.NewString(tableName, "id")
	_taskExecution.JobId = field.NewString(tableName, "job_id")
	_taskExecution.Status = field.NewInt32(tableName, "status")
	_taskExecution.StartedAt = field.NewTime(tableName, "started_at")
	_taskExecution.FinishedAt = field.NewTime(tableName, "finished_at")
	_taskExecution.Log = field.NewString(tableName, "log")

	_taskExecution.fillFieldMap()

	return _taskExecution
}

type taskExecution struct {
	taskExecutionDo

	ALL        field.Asterisk
	Id         field.String
	JobId      field.String
	Status     field.Int32
	StartedAt  field.Time
	FinishedAt field.Time
	Log        field.String

	fieldMap map[string]field.Expr
}

func (t taskExecution) Table(newTableName string) *taskExecution {
	t.taskExecutionDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t taskExecution) As(alias string) *taskExecution {
	t.taskExecutionDo.DO = *(t.taskExecutionDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *taskExecution) updateTableName(table string) *taskExecution {
	t.ALL = field.NewAsterisk(table)
	t.Id = field.NewString(table, "id")
	t.JobId = field.NewString(table, "job_id")
	t.Status = field.NewInt32(table, "status")
	t.StartedAt = field.NewTime(table, "started_at")
	t.FinishedAt = field.NewTime(table, "finished_at")
	t.Log = field.NewString(table, "log")

	t.fillFieldMap()

	return t
}

func (t *taskExecution) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *taskExecution) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 6)
	t.fieldMap["id"] = t.Id
	t.fieldMap["job_id"] = t.JobId
	t.fieldMap["status"] = t.Status
	t.fieldMap["started_at"] = t.StartedAt
	t.fieldMap["finished_at"] = t.FinishedAt
	t.fieldMap["log"] = t.Log
}

func (t taskExecution) clone(db *gorm.DB) taskExecution {
	t.taskExecutionDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t taskExecution) replaceDB(db *gorm.DB) taskExecution {
	t.taskExecutionDo.ReplaceDB(db)
	return t
}

type taskExecutionDo struct{ gen.DO }

type ITaskExecutionDo interface {
	gen.SubQuery
	Debug() ITaskExecutionDo
	WithContext(ctx context.Context) ITaskExecutionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITaskExecutionDo
	WriteDB() ITaskExecutionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITaskExecutionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITaskExecutionDo
	Not(conds ...gen.Condition) ITaskExecutionDo
	Or(conds ...gen.Condition) ITaskExecutionDo
	Select(conds ...field.Expr) ITaskExecutionDo
	Where(conds ...gen.Condition) ITaskExecutionDo
	Order(conds ...field.Expr) ITaskExecutionDo
	Distinct(cols ...field.Expr) ITaskExecutionDo
	Omit(cols ...field.Expr) ITaskExecutionDo
	Join(table schema.Tabler, on ...field.Expr) ITaskExecutionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITaskExecutionDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITaskExecutionDo
	Group(cols ...field.Expr) ITaskExecutionDo
	Having(conds ...gen.Condition) ITaskExecutionDo
	Limit(limit int) ITaskExecutionDo
	Offset(offset int) ITaskExecutionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITaskExecutionDo
	Unscoped() ITaskExecutionDo
	Create(values ...*models.TaskExecution) error
	CreateInBatches(values []*models.TaskExecution, batchSize int) error
	Save(values ...*models.TaskExecution) error
	First() (*models.TaskExecution, error)
	Take() (*models.TaskExecution, error)
	Last() (*models.TaskExecution, error)
	Find() ([]*models.TaskExecution, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.TaskExecution, err error)
	FindInBatches(result *[]*models.TaskExecution, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.TaskExecution) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITaskExecutionDo
	Assign(attrs ...field.AssignExpr) ITaskExecutionDo
	Joins(fields ...field.RelationField) ITaskExecutionDo
	Preload(fields ...field.RelationField) ITaskExecutionDo
	FirstOrInit() (*models.TaskExecution, error)
	FirstOrCreate() (*models.TaskExecution, error)
	FindByPage(offset int, limit int) (result []*models.TaskExecution, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITaskExecutionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t taskExecutionDo) Debug() ITaskExecutionDo {
	return t.withDO(t.DO.Debug())
}

func (t taskExecutionDo) WithContext(ctx context.Context) ITaskExecutionDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t taskExecutionDo) ReadDB() ITaskExecutionDo {
	return t.Clauses(dbresolver.Read)
}

func (t taskExecutionDo) WriteDB() ITaskExecutionDo {
	return t.Clauses(dbresolver.Write)
}

func (t taskExecutionDo) Session(config *gorm.Session) ITaskExecutionDo {
	return t.withDO(t.DO.Session(config))
}

func (t taskExecutionDo) Clauses(conds ...clause.Expression) ITaskExecutionDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t taskExecutionDo) Returning(value interface{}, columns ...string) ITaskExecutionDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t taskExecutionDo) Not(conds ...gen.Condition) ITaskExecutionDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t taskExecutionDo) Or(conds ...gen.Condition) ITaskExecutionDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t taskExecutionDo) Select(conds ...field.Expr) ITaskExecutionDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t taskExecutionDo) Where(conds ...gen.Condition) ITaskExecutionDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t taskExecutionDo) Order(conds ...field.Expr) ITaskExecutionDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t taskExecutionDo) Distinct(cols ...field.Expr) ITaskExecutionDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t taskExecutionDo) Omit(cols ...field.Expr) ITaskExecutionDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t taskExecutionDo) Join(table schema.Tabler, on ...field.Expr) ITaskExecutionDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t taskExecutionDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITaskExecutionDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t taskExecutionDo) RightJoin(table schema.Tabler, on ...field.Expr) ITaskExecutionDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t taskExecutionDo) Group(cols ...field.Expr) ITaskExecutionDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t taskExecutionDo) Having(conds ...gen.Condition) ITaskExecutionDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t taskExecutionDo) Limit(limit int) ITaskExecutionDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t taskExecutionDo) Offset(offset int) ITaskExecutionDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t taskExecutionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITaskExecutionDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t taskExecutionDo) Unscoped() ITaskExecutionDo {
	return t.withDO(t.DO.Unscoped())
}

func (t taskExecutionDo) Create(values ...*models.TaskExecution) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t taskExecutionDo) CreateInBatches(values []*models.TaskExecution, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t taskExecutionDo) Save(values ...*models.TaskExecution) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t taskExecutionDo) First() (*models.TaskExecution, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.TaskExecution), nil
	}
}

func (t taskExecutionDo) Take() (*models.TaskExecution, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.TaskExecution), nil
	}
}

func (t taskExecutionDo) Last() (*models.TaskExecution, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.TaskExecution), nil
	}
}

func (t taskExecutionDo) Find() ([]*models.TaskExecution, error) {
	result, err := t.DO.Find()
	return result.([]*models.TaskExecution), err
}

func (t taskExecutionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.TaskExecution, err error) {
	buf := make([]*models.TaskExecution, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t taskExecutionDo) FindInBatches(result *[]*models.TaskExecution, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t taskExecutionDo) Attrs(attrs ...field.AssignExpr) ITaskExecutionDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t taskExecutionDo) Assign(attrs ...field.AssignExpr) ITaskExecutionDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t taskExecutionDo) Joins(fields ...field.RelationField) ITaskExecutionDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t taskExecutionDo) Preload(fields ...field.RelationField) ITaskExecutionDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t taskExecutionDo) FirstOrInit() (*models.TaskExecution, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.TaskExecution), nil
	}
}

func (t taskExecutionDo) FirstOrCreate() (*models.TaskExecution, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.TaskExecution), nil
	}
}

func (t taskExecutionDo) FindByPage(offset int, limit int) (result []*models.TaskExecution, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t taskExecutionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t taskExecutionDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t taskExecutionDo) Delete(models ...*models.TaskExecution) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *taskExecutionDo) withDO(do gen.Dao) *taskExecutionDo {
	t.DO = *do.(*gen.DO)
	return t
}
