name: kk_scheduler
services:
  kk_scheduler:
    image: cruvie/kk_scheduler:latest
    container_name: kk_scheduler
    restart: unless-stopped
    environment:
      KK_Schedule: "prod"
    depends_on:
      - test-postgres
    ports:
      - "8666:8666"
      - "8667:8667"
      - "8668:8668"
    volumes:
      - ./config.toml:/kk_scheduler/config.toml
      - ./logs:/kk_scheduler/logs
    networks:
      - kk_scheduler

  test-postgres:
    image: postgres:latest
    container_name: test-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: testpg
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql
    networks:
      - kk_scheduler

networks:
  kk_scheduler:
    external: true