GrpcPort = 8666
HttpPort = 8667
WebPort = 8668

[Store]
Choose="PG"
[Store.PG.DSN]
Host = "127.0.0.1"
Port = 5432
User = "postgres"
Password = "testpg"
DBName = "kk_scheduler"
Schema = ""
SSLMode = "disable"
TimeZone = "UTC"